FROM node:12.22-alpine3.14

# from frontend root: docker build -f Dockerfile.dev -t nodedev .
# from frontend root: docker run -v ~/repos/banking/frontend/src:/app/src -p 8080:8080 -it nodedev
# définit le dossier 'app' comme dossier de travail
WORKDIR /app

RUN apk add --no-cache bash

COPY ./yarn.lock ./package.json /app/
ADD ./src /app/src
ADD ./public /app/public
ADD ./bin /app/bin 
  
# installe les dépendances du projet
RUN yarn install

ENTRYPOINT [ "yarn", "serve" ]