FROM node:lts-alpine

# from banking root: docker build -t nodedev - < Dockerfile.dev
# from banking root: docker run -v ~/repos/banking/frontend:/app -p 8080:8080 -it nodedev
# définit le dossier 'app' comme dossier de travail
WORKDIR /app

#
RUN apk add --no-cache bash

# copie 'package.json' et 'package-lock.json' (si disponible)
COPY . ./

# installe les dépendances du projet
RUN yarn install

# COPY public ./public
# COPY src ./src
# COPY babel.config.js ./ 
 
ENTRYPOINT [ "yarn", "serve" ]