FROM node:12.22-alpine3.14 as build-stage

WORKDIR /app
RUN apk add --no-cache bash
COPY ./yarn.lock ./package.json /app/
  
RUN yarn install

ADD ./src /app/src
ADD ./public /app/public
ADD ./bin /app/bin 

ARG VUE_APP_MODE
ARG BACKEND_BASE_URL
RUN VUE_APP_MODE=${VUE_APP_MODE} BACKEND_BASE_URL=${BACKEND_BASE_URL} yarn build 

FROM nginx:1.21.6-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]