services:
  # flask server
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    command: "flask run"
    environment:
      - FLASK_APP=banking
      - FLASK_RUN_HOST=0.0.0.0
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=banking
      - MODEL_PATH=/models
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data/models:/models
    depends_on:
      - database

  # vue client
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        VUE_APP_API: localhost:5000
        VUE_APP_MODE: production
    ports:
      - 8080:80

  # message broker for background tasks
  redis:
    image: redis:6-alpine
    ports: 
      - 6379:6379

  database:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=banking
      - POSTGRES_PASSWORD=password
      - PGDATA=/data
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/data

  # worker for celery background tasks
  celery_worker:
    build:
      context: server/
      dockerfile: Dockerfile
    command: "celery -A banking.celery worker"
    environment:
      - FLASK_APP=banking
      - FLASK_RUN_HOST=0.0.0.0
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=banking
      - MODEL_PATH=/models
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - server
      - database
    volumes:
      - ./data/models:/models

