services:
  # flask server
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: "flask run"
    environment:
      FLASK_APP: banking
      FLASK_RUN_HOST: 0.0.0.0
      DB_FILE: /data/db.db
      MODEL_PATH: /models
      FLASK_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - db_volume:/data
      - models_volume:/models

  # vue client
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        VUE_APP_API: localhost:5000
        VUE_APP_MODE: production
    ports:
      - 8080:80

  # message broker for background tasks
  redis:
    image: redis:6-alpine
    ports: 
      - 6379:6379

  # worker for celery background tasks
  celery_worker:
    build:
      context: server/
      dockerfile: Dockerfile
    command: "celery -A banking.celery worker"
    environment:
      FLASK_APP: banking
      FLASK_RUN_HOST: 0.0.0.0
      DB_FILE: /data/db.db
      MODEL_PATH: /models
      FLASK_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - server
    volumes:
      - db_volume:/data
      - models_volume:/models

volumes:
  db_volume:
  models_volume: