services:
  # flask server
  server:
    image: rmormont/banking-server:latest
    restart: always
    ports:
      - ${BACKEND_PORT:-5000}:5000
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=banking
      - REDIS_HOST=redis
      - REDIS_PORT=6379docker 
      - JWT_SECRET_KEY=${JWT_SECRET}
    volumes:
      - ./data/models:/models
    depends_on:
      - database

  # vue client
  frontend:
    image: rmormont/banking-ui:latest
    environment:
      - BACKEND_BASE_URL=http://${BACKEND_HOST:-localhost}:${BACKEND_PORT:-5000}
    ports:
      - ${FRONTEND_PORT:-8080}:80

  # message broker for background tasks
  redis:
    image: redis:6-alpine

  database:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=banking
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data
    volumes:
      - ./data/db:/data

  # worker for celery background tasks
  celery_worker:
    image: rmormont/banking-task-runner:latest
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=banking
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - server
      - database
    volumes:
      - ./data/models:/models

