"""empty message

Revision ID: 72ac59e8dfb2
Revises: d8564e38689c
Create Date: 2022-05-27 11:20:01.502704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ac59e8dfb2'
down_revision = 'd8564e38689c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewrite_group', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewrite_group', 'name')
    # ### end Alembic commands ###
