"""remove model_file.target column

Revision ID: 9dae718eeba2
Revises: 1ac3ef49516b
Create Date: 2025-03-02 18:15:32.098665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dae718eeba2'
down_revision = '1ac3ef49516b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_model_file', 'target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model_file', sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
