"""empty message

Revision ID: f4f90ab77b43
Revises: 5a30197c7053
Create Date: 2023-12-29 02:11:00.422901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f90ab77b43'
down_revision = '5a30197c7053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('id_is_duplicate_of', sa.Integer(), nullable=True, server_default=None))
    op.create_foreign_key(None, 'transaction', 'transaction', ['id_is_duplicate_of'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'id_is_duplicate_of')
    # ### end Alembic commands ###
